### ISSUE TITLE
S3 update excruciatingly slow

### ISSUE THREAD

**Issue by MikeVlad6** [alberanid/imdbpy#336]
Hi, 
I'm using the code from the `s32imdbpy` script to update on a regular basis the local database.  I've read carefully [this section](https://imdbpy.readthedocs.io/en/latest/usage/s3.html) from the documentation and the process runs but it takes nowhere near 2 hours, more like forever:). 
I've tried different variations of BLOCKSIZE, the result is mostly the same. The actual problem being that after some million entries i keep hitting the response timeout limit.

I know that this probably is not `imdbpy`-problem but if you have any tips on improving speed, they would be really helpful.  Would it be faster to open the `tsv` files, do the edits from `generate_content` (add soundex etc), write to a csv and use a bulk import method?

I suspect that it has something to do with **mysql instance being ran inside docker** (maybe). Is postresql faster?
Here's my mysql docker config: (tried qith myIsam and InnoDB)
```
  myimdb_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856 --net_read_timeout=700 --default-storage-engine=MyIsam
    container_name: MOVIELIB_Mysql
    restart: always
    ports:
    - ${MYSQL_MYIMDB_PORT}:${MYSQL_MYIMDB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MYIMDB_PASS}
      MYSQL_TCP_PORT: ${MYSQL_MYIMDB_PORT}
    volumes:
    - ${MYSQL_MYIMDB_DB_LOCATION}:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "$MYSQL_MYIMDB_HOST", "-P$MYSQL_MYIMDB_PORT"]
      timeout: 20s
      retries: 50
```

Thanks for the great work!
